# Generated by Django 5.1.2 on 2024-10-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('property_type', models.CharField(choices=[('buy', 'Buy Property'), ('sell', 'Sell Property')], max_length=50)),
                ('property_category', models.CharField(choices=[('agriculture', 'Agriculture'), ('layouts', 'Layouts'), ('industrial', 'Industrial'), ('commercial', 'Commercial'), ('residential', 'Residential')], max_length=50)),
                ('location', models.CharField(max_length=250)),
                ('square_yards', models.CharField(max_length=50)),
                ('budget_range', models.CharField(max_length=50)),
            ],
        ),
    ]
